# Generated by Django 5.0.1 on 2024-01-23 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditapproval", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
